name: React App CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  sonar-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1.0.0
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  build:
    name: Build React App
    runs-on: ubuntu-latest
    needs: sonar-analysis

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  # deploy:
  #   name: Deploy to VM
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Download Build Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: react-build
  #         path: build

  #     - name: Cleanup and Prepare Target (via SSH)
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_KEY }}
  #         script: |
  #           sudo chmod -R 777 /var/www/html
  #           sudo rm -rf /var/www/html/*

  #     - name: Copy Files to Remote Server
  #       uses: appleboy/scp-action@v1.0.4
  #       with:
  #         host: ${{ secrets.SSH_HOST }}
  #         username: ${{ secrets.SSH_USER }}
  #         key: ${{ secrets.SSH_KEY }}
  #         source: "build/*"
  #         target: "/var/www/html"
